#!/bin/bash

function get_ca-cert(){
  docker run --rm \
  -v $(pwd)/certs:/data \
  alpine:3.5 sh -c \
  "apk add -U ca-certificates \
  && cp /etc/ssl/certs/ca-certificates.crt /data/ca-certificates.crt"
}

function compile(){
  local GOARCH="${1}"
  docker run --rm -t \
  -e GOARCH -e CGO_ENABLED=0 \
  -v $(pwd):/data \
  golang:1.8 bash -c \
  "go get -v -d github.com/xenolf/lego \
  && cd \$GOPATH/src/github.com/xenolf/lego \
  && go get -v -d ./... \
  && go build -a --installsuffix cgo --ldflags='-s' -o /data/lego-\$GOARCH"
}

# Compile for different GOARCHS
compile arm
compile amd64

# Make the result executable
chmod a+x lego-*
