#!/bin/bash

function get_ca_cert(){
  docker run --rm \
  -v $(pwd)/content/etc/ssl/certs:/data \
  alpine:3.6 sh -c \
  "apk add -U ca-certificates \
  && cp /etc/ssl/certs/ca-certificates.crt /data/ca-certificates.crt"
}

function compile(){
  docker run --rm -t \
  -e GOARCH=$DOCKER_TAG \
  -e CGO_ENABLED=0 \
  -v $(pwd):/data \
  golang:1.8 bash -c \
  "go get -v -d github.com/xenolf/lego \
  && cd \$GOPATH/src/github.com/xenolf/lego \
  && go get -v -d ./... \
  && go build -a --installsuffix cgo --ldflags='-s' -o /data/lego-\$GOARCH"
}

mkdir -p content/etc/ssl/certs
get_ca_cert

#echo "==> Compile for different GOARCH"
#compile ${DOCKER_TAG}
#chmod a+x lego-${DOCKER_TAG}
